apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: dev
  labels:
    app: product
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      restartPolicy: Always
      containers:
        - name: library
          image: docker.io/adrian2606/inditex-hexagonal-api-test:v1
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:products
            - name: SERVER_PORT
              value: "8080"
