apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: dev
  labels:
    app: product
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: product-port
  selector:
    app: product
  type: NodePort